services:
  backend:
    container_name: container_backend
    build: 
      context: .
      target: production
    ports:
      - "8080:8080"
    restart: always
    networks:
      - network_connect
networks:
  network_connect:
    external: true
volumes:
  backend_logs: