services:
  mongodb:
    image: 'mongo'
    container_name: container_mongo
    restart: "always"
    env_file:
      - ./env/env_mongo.env
    volumes:
      - mongo_data:/data/db
    networks:
      - network_data
  backend:
    container_name: container_backend
    build: 
      context: .
      target: production
    ports:
      - "8080:8080"
    environment:
    - MONGO_URL=${MONGO_URL_PROD}
    restart: always
    networks:
      - network_connect
networks:
  network_connect:
    external: bridge
  network_data:
    driver: bridge
volumes:
  mongo_data:
  backend_logs: