name: Buid Backend Dev
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

    paths:
      - "**"
jobs:
  build-deploy:
    name: Build and Development Back-End
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check sysntax
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Check Code
        run: npm run lint
        continue-on-error: true

      - name: Dockerfile Syntax Check
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Build Test
        run: npm run build
        env:
          MONGO_URL: ${{ secrets.MONGO_URL_DEV }}

      - name: Create file for dev
        run: |
          mkdir -p ./env
          echo "MONGO_URL=${{ secrets.MONGO_URL_DEV }}" > ./env/development.env

      - name: Build Docker Image
        run: docker compose -f docker-compose.dev.yml build
        env:
          MONGO_URL: ${{ secrets.MONGO_URL_DEV }}
